### ISSUE TITLE
a2s.ainfo() leading to TypeError: raise_on_error() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#14]
Hello! I was working with your library and encountred such error:
```
Traceback (most recent call last):
  File "/app/src/updater.py", line 82, in update_server
    serverObj = await c.ARKServer(ip).AGetInfo() # get info about server
  File "/app/src/classes.py", line 37, in AGetInfo
    server = await a2s.ainfo((self.address,self.port)) # get server data
  File "/usr/local/lib/python3.7/site-packages/a2s/info.py", line 277, in ainfo
    resp_data = await conn.request(b"\x54Source Engine Query\0")
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 92, in request
    return await self.recv()
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 84, in recv
    self.protocol.raise_on_error()
TypeError: raise_on_error() takes 0 positional arguments but 1 was given
```
You can find code [here](https://github.com/Nereg/ARKMonitorBot/blob/master/src/classes.py) ([ARKServer.AGetInfo()](https://github.com/Nereg/ARKMonitorBot/blob/bd3006ab54c0471f9fde4f4a47585a0137f03f42/src/classes.py#L33) and [PlayersList.AgetPlayersList()](https://github.com/Nereg/ARKMonitorBot/blob/bd3006ab54c0471f9fde4f4a47585a0137f03f42/src/classes.py#L146)). But sadly I couldn't reproduce that error on my computer so maybe it is affected by how many request I send (I update info about servers every 30 seconds or so)

**Comment by Nereg** [comment]
I found that in [raise_on_error](https://github.com/Yepoleb/python-a2s/blob/aa418c9e8d1f479384d3e991fc9647957f8b46cf/a2s/a2sasync.py#L50) you forgot to add `self` as first parameter of class function. I tested it and it works well on test stand but I will test it on my production before submitting pull request
