### ISSUE TITLE
TypeError: raise_on_error() takes 0 positional arguments but 1 was given

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#22]
Hello ! I got this strange error on my main server :
```
Traceback (most recent call last):
  File "/app/src/updater.py", line 157, in printer
    result = await self.update_server(server[0]) # update server
  File "/app/src/updater.py", line 119, in update_server
    serverObj = await c.ARKServer(ip).AGetInfo() # get info about server
  File "/app/src/classes.py", line 48, in AGetInfo
    server = await a2s.ainfo((self.address,self.port)) # get server data
  File "/usr/local/lib/python3.7/site-packages/a2s/info.py", line 277, in ainfo
    resp_data = await conn.request(b"\x54Source Engine Query\0")
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 92, in request
    return await self.recv()
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 84, in recv
    self.protocol.raise_on_error()
TypeError: raise_on_error() takes 0 positional arguments but 1 was given
```
Library version is `1.2.0`. Python version is `3.7.4 Linux 32-bits` Server ip is `51.81.75.174:27016`
Also my test scripts don't fail like that. They report that the server is offline, But version there is `1.1.5` so I will try to update them and see if I can reproduse this.  
P.S. Hey I got this error only on async version ! That smt at least to narrow search area.
Embarrassing AF

**Comment by Yepoleb** [comment]
You reported this error yourself 3 months ago in #14! Please update to at least 1.2.1.
