### ISSUE TITLE
OSError: [Errno 113] No route to host

### ISSUE THREAD

**Issue by Nereg** [Yepoleb/python-a2s#23]
Hello! So I discovered this new error in my logs. Library's version is `1.2.1` Here is it's stacktrace:
```
Traceback (most recent call last):
  File "/app/src/updater.py", line 157, in printer
    result = await self.update_server(server[0]) # update server
  File "/app/src/updater.py", line 119, in update_server
    serverObj = await c.ARKServer(ip).AGetInfo() # get info about server
  File "/app/src/classes.py", line 48, in AGetInfo
    server = await a2s.ainfo((self.address,self.port)) # get server data
  File "/usr/local/lib/python3.7/site-packages/a2s/info.py", line 277, in ainfo
    resp_data = await conn.request(b"\x54Source Engine Query\0")
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 92, in request
    return await self.recv()
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 84, in recv
    self.protocol.raise_on_error()
  File "/usr/local/lib/python3.7/site-packages/a2s/a2sasync.py", line 54, in raise_on_error
    raise error
  File "/usr/local/lib/python3.7/asyncio/selector_events.py", line 957, in _read_ready
    data, addr = self._sock.recvfrom(self.max_size)
OSError: [Errno 113] No route to host
```
And I pinged and traceroute'ed host and it is up and running. Here is output of those:
```
root@7f8ba9b3d48e:/app# traceroute 31.214.160.82
traceroute to 31.214.160.82 (31.214.160.82), 30 hops max, 60 byte packets
 1  172.19.0.1 (172.19.0.1)  0.076 ms  0.014 ms  0.019 ms
 2  172.31.164.122 (172.31.164.122)  0.097 ms  0.053 ms  0.037 ms
 3  172.31.160.21 (172.31.160.21)  0.781 ms  1.133 ms  1.082 ms
 4  172.17.23.111 (172.17.23.111)  0.374 ms  0.339 ms  0.304 ms
 5  185.61.95.92 (185.61.95.92)  1.745 ms  1.778 ms  1.839 ms
 6  as199524.ix.dataix.ru (178.18.226.230)  46.742 ms  42.770 ms  43.334 ms
 7  10.255.4.172 (10.255.4.172)  51.857 ms  44.531 ms  48.388 ms
 8  92.223.125.75 (92.223.125.75)  44.268 ms  44.522 ms  42.297 ms
 9  95.156.239.10 (95.156.239.10)  39.957 ms  53.589 ms  55.457 ms
10  31.214.160.82 (31.214.160.82)  43.247 ms !X  39.988 ms !X  39.954 ms !X
```
And ping:
```
root@7f8ba9b3d48e:/app# ping 31.214.160.82
PING 31.214.160.82 (31.214.160.82) 56(84) bytes of data.
64 bytes from 31.214.160.82: icmp_seq=1 ttl=53 time=39.4 ms
64 bytes from 31.214.160.82: icmp_seq=2 ttl=53 time=39.5 ms
64 bytes from 31.214.160.82: icmp_seq=3 ttl=53 time=39.4 ms
^C
--- 31.214.160.82 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 6ms
```
So there should not be such error. And also steam server viewer and `ISteamApps/GetServersAtAddress` shows no servers. But maybe they are offline and it should not give such error. But at least I would like to se this error mentioned in README
P.S. wow github why you referenced my commit

**Comment by Yepoleb** [comment]
Sorry for taking so long to get back on this. Routing errors sometimes happen randomly, even if they shouldn't. I can almost certainly say that this problem is way downstream from this library's code, so there's nothing I can do about it. A note about the exception has been added to the Readme in 9d43f53eee591a385a7a433f9e4845e780265f5d. Thanks for reporting!
