### ISSUE TITLE
socket.timeout: timed out

### ISSUE THREAD

**Issue by ComputersWithTimo** [Yepoleb/python-a2s#30]
Tested on AlmaLinux 8.5 using Python 3.9 and Ubuntu 20.04 using Python 3.8. No extra packages installed. Tested on different networks and with different source servers (mostly CS:GO).

Steps to reproduce:

1. Install a clean Linux
2. pip3 install python-a2s or git clone and install (doesn't seems to make a difference)
3. run the example code:
```
>>> import a2s
>>> address = ("stomping.kinofnemu.net", 27015)
>>> a2s.info(address)
```
4. get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/a2s/info.py", line 182, in info
    return request_sync(address, timeout, encoding, InfoProtocol)
  File "/usr/local/lib/python3.8/dist-packages/a2s/a2s_sync.py", line 22, in request_sync
    response = request_sync_impl(conn, encoding, a2s_proto)
  File "/usr/local/lib/python3.8/dist-packages/a2s/a2s_sync.py", line 28, in request_sync_impl
    resp_data = conn.request(a2s_proto.serialize_request(challenge))
  File "/usr/local/lib/python3.8/dist-packages/a2s/a2s_sync.py", line 92, in request
    return self.recv()
  File "/usr/local/lib/python3.8/dist-packages/a2s/a2s_sync.py", line 67, in recv
    packet = self._socket.recv(65535)
socket.timeout: timed out
```

**Comment by Yepoleb** [comment]
The example server has been shut down apparently. Use `("chi-1.us.uncletopia.com", 27015)` instead.
