### ISSUE TITLE
NameError: name 'BufferExhaustedError' is not defined

### ISSUE THREAD

**Issue by andykais** [Yepoleb/python-a2s#4]
Hi, I have two errors going on here. The first is that I am receiving a BufferExhaustedError when calling `a2s.info(address)`, though the same address responds with a valid response when using the old [python-valve](https://github.com/serverstf/python-valve) repo. The second error is that BufferExhaustedError appears to be undefined. Traceback:

```
Traceback (most recent call last):
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/info.py", line 199, in parse_source
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/byteio.py", line 41, in read_uint8
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/byteio.py", line 33, in unpack_one
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/byteio.py", line 30, in unpack
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/byteio.py", line 17, in read
a2s.exceptions.BufferExhaustedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "query_server-a2s.py", line 33, in <module>
    info_dump = query_server(host, port)
  File "query_server-a2s.py", line 18, in query_server
    info = a2s.info(sqp_address)
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/info.py", line 256, in info
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/python_a2s-1.1.2-py3.6.egg/a2s/info.py", line 200, in parse_source
NameError: name 'BufferExhaustedError' is not defined
```
unfortunately I cannot give you the address I am polling because it is proprietary.

**Comment by andykais** [comment]
If this is at all helpful, I can share this information from the `python-valve` response
```
  'protocol': 1,
  'response_type': 73,
```

**Comment by Yepoleb** [comment]
I've fixed the NameError in version 1.1.3. Please try it and if there are still issues, provide the game name, version and mods installed.

**Comment by andykais** [comment]
seeing this error now on version 1.1.3
```
Traceback (most recent call last):
  File "query_server-a2s.py", line 33, in <module>
    info_dump = query_server(host, port)
  File "query_server-a2s.py", line 18, in query_server
    info = a2s.info(sqp_address)
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/a2s/info.py", line 256, in info
    resp = parse_source(reader)
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/a2s/info.py", line 203, in parse_source
    if resp.has_port:
  File "/Users/andrew/.virtualenvs/python-valve-a2s/lib/python3.6/site-packages/a2s/info.py", line 91, in has_port
    return bool(self.edf & 0x80)
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'
```

thanks for your help!

**Comment by Yepoleb** [comment]
Dammit, I should have seen this coming. New version is up.

**Comment by andykais** [comment]
that did the trick! 😄Thank you so much!

**Comment by Yepoleb** [comment]
You're welcome. Sorry for not testing this properly :grimacing:
