### ISSUE TITLE
a2s.arules has data error while a2s.rules doesnt

### ISSUE THREAD

**Issue by mastercoms** [Yepoleb/python-a2s#55]
```
Exception in callback _ProactorDatagramTransport._loop_reading(<_OverlappedF...sion\x001.3.'>)
handle: <Handle _ProactorDatagramTransport._loop_reading(<_OverlappedF...sion\x001.3.'>)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "asyncio\proactor_events.py", line 589, in _loop_reading
    self._protocol.datagram_received(data, addr)
  File "site-packages\a2s\a2s_async.py", line 70, in datagram_received
    self.fragment_buf.append(decode_fragment(payload))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "site-packages\a2s\a2s_fragment.py", line 35, in decode_fragment
    frag.payload = bz2.decompress(reader.read())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "bz2.py", line 333, in decompress
    res = decomp.decompress(data)
          ^^^^^^^^^^^^^^^^^^^^^^^
OSError: Invalid data stream
```

This is being used in a asyncio.gather for many different servers if that matters.

**Comment by Nereg** [comment]
If you can, please isolate the server that is causing that, and get a capture of the traffic on the network. You could do that with Wireshark

**Comment by Yepoleb** [comment]
Please provide a server address for me to be able to debug this.
