### ISSUE TITLE
Error a2s.exceptions.BrokenMessageError: Invalid packet header: b'\x00\x00\x00\x00'

### ISSUE THREAD

**Issue by Maglctea** [Yepoleb/python-a2s#61]
Hi! When I try to get information about the DayZ server located at 46.42.17.177:27016, I come across an error (see below).

At this address (it is specified in the documentation), information is displayed or not https://sourcequery.yepoleb.at/query?server=46.42.17.177%3A27016

What could be the problem?

```py
@dataclass
class ServerBannerInfo:
    status: str
    players: int
    max_players: int
    version: str
    map: str


async def get_server_info(address: str, query_port: int) -> ServerBannerInfo | None:
    server = (address, query_port)
    try:
        info: SourceInfo = await a2s.ainfo(server, timeout=DEFAULT_TIMEOUT, encoding=DEFAULT_ENCODING)
    except asyncio.TimeoutError:
        logger.warning(f'Server {address}:{query_port} is not responding for a long time')
        return None
    except ConnectionRefusedError:
        logger.warning(f'Server {address}:{query_port} refused to connect')
        return None

    server_info = ServerBannerInfo(
        status='online',
        players=info.player_count,
        max_players=info.max_players,
        version=info.version,
        map=info.map_name
    )

    return server_info
```

```
2024-12-15 22:06:23.752351: NOVA Revival: Traceback (most recent call last):
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\src\dayz\presentation\bot\service\server.py", line 80, in update_embeds_service
    server_banner_info=await get_server_info(server.address, server.query_port),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\src\dayz\presentation\bot\service\server.py", line 29, in get_server_info
    info: SourceInfo = await a2s.ainfo(server, timeout=DEFAULT_TIMEOUT, encoding=DEFAULT_ENCODING)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\info.py", line 185, in ainfo
    return await request_async(address, timeout, encoding, InfoProtocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 22, in request_async
    response = await request_async_impl(conn, encoding, a2s_proto)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 28, in request_async_impl
    resp_data = await conn.request(a2s_proto.serialize_request(challenge))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 134, in request
    return await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 126, in recv
    self.protocol.raise_on_error()
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 96, in raise_on_error
    raise error
a2s.exceptions.BrokenMessageError: Invalid packet header: b'\x00\x00\x00\x00'
Traceback (most recent call last):
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\src\dayz\presentation\bot\service\server.py", line 80, in update_embeds_service
    server_banner_info=await get_server_info(server.address, server.query_port),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\src\dayz\presentation\bot\service\server.py", line 29, in get_server_info
    info: SourceInfo = await a2s.ainfo(server, timeout=DEFAULT_TIMEOUT, encoding=DEFAULT_ENCODING)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\info.py", line 185, in ainfo
    return await request_async(address, timeout, encoding, InfoProtocol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 22, in request_async
    response = await request_async_impl(conn, encoding, a2s_proto)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 28, in request_async_impl
    resp_data = await conn.request(a2s_proto.serialize_request(challenge))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 134, in request
    return await self.recv()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 126, in recv
    self.protocol.raise_on_error()
  File "C:\Users\Magictea\PycharmProjects\Frilance\analitics_dayz_servers\.venv\Lib\site-packages\a2s\a2s_async.py", line 96, in raise_on_error
    raise error
a2s.exceptions.BrokenMessageError: Invalid packet header: b'\x00\x00\x00\x00'
```

**Comment by Yepoleb** [comment]
I've tried querying the server a few times and it fails about half the time because the server is sending garbage data (64 bytes just zeros). This is not a bug in your or my code, but in the server software. To work around this you can retry the request a few times with a short timeout, 5 times with 300ms (that's timeout=0.3) should be good. If you still get no valid response the only option is to fail, there is nothing we can do.
